### ISSUE TITLE
catalogdb.sdss_id_to_catalog broken query syntax

### ISSUE THREAD

**Issue by havok2063** [sdss/sdssdb#260]
The `sdssdb` peewee syntax for using the new `catalogdb.sdss_id_to_catalog` view fails to load.  Looks like there's a missing column? 

```
from sdssdb.peewee.sdss5db import database as pdb, catalogdb
catalogdb.SDSS_ID_To_Catalog.select().dicts().first()
```
gives the following error:
```
peewee.ProgrammingError: column t1.allstar_dr17_synspec_rev1_apstar_id does not exist
LINE 1: SELECT "t1"."pk", "t1"."sdss_id", "t1"."allstar_dr17_synspec...
```

Full traceback:
```
[ERROR]: Traceback (most recent call last):
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 3311, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.UndefinedColumn: column t1.allstar_dr17_synspec_rev1_apstar_id does not exist
LINE 1: SELECT "t1"."pk", "t1"."sdss_id", "t1"."allstar_dr17_synspec...
                                          ^
HINT:  Perhaps you meant to reference the column "t1.allstar_dr17_synspec_rev1__apstar_id".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-c9b3ba586259>", line 1, in <module>
    catalogdb.SDSS_ID_To_Catalog.select().dicts().first()
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 2025, in inner
    return method(self, database, *args, **kwargs)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 2284, in first
    return self.peek(database, n=n)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 2025, in inner
    return method(self, database, *args, **kwargs)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 2275, in peek
    rows = self.execute(database)[:n]
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 2025, in inner
    return method(self, database, *args, **kwargs)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 2096, in execute
    return self._execute(database)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 2269, in _execute
    cursor = database.execute(self)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 3319, in execute
    return self.execute_sql(sql, params)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 3309, in execute_sql
    with __exception_wrapper__:
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 3077, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 196, in reraise
    raise value.with_traceback(tb)
  File "/Users/brian/anaconda3/envs/valis_solara/lib/python3.10/site-packages/peewee.py", line 3311, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: column t1.allstar_dr17_synspec_rev1_apstar_id does not exist
LINE 1: SELECT "t1"."pk", "t1"."sdss_id", "t1"."allstar_dr17_synspec...
                                          ^
HINT:  Perhaps you meant to reference the column "t1.allstar_dr17_synspec_rev1__apstar_id".
```

**Comment by albireox** [comment]
Should be fixed now. The double underscores were missing in the model definitions.
